export const apiMethods = {
  GET: 'GET',
  POST: 'POST',
  PUT: 'PUT',
  DELETE: 'DELETE',
};

export const httpStatusCode = {
  SUCCESS: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  FORBIDDEN: 401,
  INTERNAL_ERRORS: 500,
  SESSION_TIMEOUT: 408,
};

export const components = {
  LOGIN: 'LOGIN',
  SIGNUP: 'SIGNUP',
  USER_SIGN: 'USER_SIGN',
  SUCCESS: 'SUCCESS',
  HOME: 'HOME',
  FORGET: 'FORGET',
  GET_SSO_USER_DETAILS: 'GET_SSO_USER_DETAILS',
  OTP_VERIFY: 'OTP_VERIFY',
  RESET: 'RESET',
  DASHBOARD: 'DASHBOARD',
  ANNOUNCEMENT: 'ANNOUNCEMENT',
  NETWORK_HEALTH: 'NETWORK_HEALTH',
  HEALTH_CHARTS: 'HEALTH_CHARTS',
  TICKETS: 'TICKETS',
  ADD_TICKET: 'ADD_TICKET',
  EDIT_TICKET: 'EDIT_TICKET',
  VIEW_TICKET: 'VIEW_TICKET',
  CHATS: 'CHATS',
  EDIT_USER: 'EDIT_USER',
  TWO_FACTOR: 'TWO_FACTOR',
  NOTIFICATION: 'NOTIFICATION',
  PROFILE: 'PROFILE',
  TEST_TICKET: 'TEST_TICKET',
  STATISTICS: 'STATISTICS',
  TERMSANDCONDITIONS: 'TERMSANDCONDITIONS',
  PRIVACYPOLICY: 'PRIVACYPOLICY',
  TICKETMOB: 'TICKETMOB',
};

export const gaEvents = {
  LOGIN_VIA_EMAIL: 'login_via_email',
  LOGIN_VIA_GOOGLE: 'login_via_google',
  LOGIN_VIA_MICROSOFT: 'login_via_microsoft',
  NAVIGATE_FORGOT_PASSWORD: 'navigate_forgot_password',
  NAVIGATE_SIGNUP: 'navigate_signup',
  UPDATE_MOBILE_NUMBER: 'update_mobile_number',
  VERIFY_EMAIL_OTP: 'verify_email_otp',
  RESEND_OTP_EMAIL: 'resend_otp_email',
  NAVIGATE_USERS_LIST: 'navigate_users_list',
  NAVIGATE_ANNOUNCEMENTS: 'navigate_announcements',
  NAVIGATE_TICKETS_LIST: 'navigate_tickets_list',
  NAVIGATE_DASHBOARD: 'navigate_dashboard',
  NAVIGATE_CHAT: 'navigate_chat',
  NAVIGATE_FRESHCHAT: 'navigate_freshchat',
  OPEN_NOTIFICATION_SLIDER: 'open_notification_slider',
  NAVIGATE_NOTIFICATIONS: 'navigate_notifications',
  NAVIGATE_PROFILE: 'navigate_profile',
  USER_LOGOUT: 'user_logout',
  CREATE_ACCOUNT_SIGNUP: 'create_account_signup',
  NAVIGATE_LOGIN: 'navigate_login',
  SEND_OTP: 'send_otp_mobile',
  RESEND_OTP: 'resend_otp_mobile',
  SEND_RESET_PASSWORD_LINK: 'send_reset_password_link',
  RESET_PASSWORD: 'reset_password',
  UPDATE_SSO_USER_DETAILS: 'update_sso_user_details',
  APPROVE_USER: 'approve_user',
  OPEN_CREATE_USER: 'open_create_user',
  CREATE_USER: 'create_user',
  NAVIGATE_EDIT_USER: 'navigate_edit_user',
  OPEN_DELETE_USER: 'open_delete_user',
  DELETE_USER: 'delete_user',
  CANCEL_DELETE_USER: 'cancel_delete_user',
  UPDATE_USER_DETAILS: 'update_user_details',
  SEND_ANNOUNCEMENT: 'send_announcement',
  ENABLE_EDIT_USER: 'enable_edit_user',
  NAVIGATE_USERS_OR_TICKETS: 'navigate_users_tickets',
  UPDATE_PROFILE_DETAILS: 'update_profile_details',
  NAVIGATE_VIEW_TICKET: 'navigate_view_ticket',
  NAVIGATE_ADD_TICKET: 'navigate_add_ticket',
  NAVIGATE_EDIT_TICKET: 'navigate_edit_ticket',
  CREATE_NEW_TICKET: 'create_new_ticket',
  UPDATE_TICKET_DETAILS: 'update_ticket_details',
  CONTACT_SALES: 'contact_sales',
  ADMIN_STATISTICS: 'admin_statistics',
  TERMS_AND_CONSDITIONS: 'terms_and_consitions',
  PRIVACY_POLICY: 'PRIVACY_POLICY',
};

export const aboutSignet =
  'Founded in 1974, SIGNET Electronic Systems Inc. (SIGNET) has grown from a one-person installation services contractor to a 160-person complete technology solutions provider. From design, engineering and installation of a fully independent critical technology system to remote monitoring services, SIGNET delivers comprehensive technology expertise in the areas of communications, security, healthcare communications, wireless connectivity, and mission critical technologies program management.';
